name: "broker_analytics"
version: "1.0"
config-version: 2
profile: "broker_analytics"
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
models:
  broker_analytics:
    +materialized: table
    staging:
      +schema: stg
    dim:
      +schema: dim
    fact:
      +schema: fact
